services:
    trikoder_manifest_asset.manifest_asset_extension:
        class: Trikoder\ManifestAssetBundle\Twig\ManifestAssetExtension
        arguments: ["@trikoder_manifest_asset.manifest_reader", "@request_stack", "%trikoder_manifest_asset.web_path%"]
        tags:
            - { name: twig.extension }

    trikoder_manifest_asset.manifest_reader:
        class: Trikoder\ManifestAssetBundle\Service\ManifestReaderService
        arguments: ["@kernel"]
