version: '3'
services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_GROUP_ID=${HOST_GROUP_ID}
      - SSH_AUTH_SOCK=/tmp/ssh_auth_sock
    volumes:
      - .:/app/src
      - ${SSH_AUTH_SOCK}:/tmp/ssh_auth_sock
